name: KH BYUN
author: Novemberde
baseurl: 
description: Development Log
github: http://www.github.com/novemberde
linkedin: https://www.linkedin.com/in/kyuhyun-byun-70a228115/
disqus: novemberde-github-io
# email: 


# highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
